Parameters:
  LambdaMetricsAlarmName:
    Type: String
    Default: lambda-metrics-alarm
  CloudWatchMetricsNS:
    Type: String
    Default: MyCloudTrailMetrics
  CloudWatchMetricName:
    Type: String
    Default: emergency_info
  SNSEndpoint:
    Type: String
    Default: jing.sun@rea-group.com
  SNSTopicName:
    Type: String
    Default: LambdaBadLogAlarm

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: ../lambda-custom
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: "nodejs12.x"
      Timeout: 900

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
      Policies:
        - PolicyName: lambda-policy-log
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:*:*:log-group:/aws/lambda/*:*

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${LambdaFunction}

  AlarmSNSTopic:
    Properties:
      Subscription:
        - Endpoint: !Ref SNSEndpoint
          Protocol: email
      TopicName: !Ref SNSTopicName
    Type: AWS::SNS::Topic

  CloudWatchTriggerLambdaRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: "rate(1 minute)"
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: 1

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt CloudWatchTriggerLambdaRule.Arn

  MetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref LambdaLogGroup
      FilterPattern: INFO Emergency
      MetricTransformations:
        - MetricNamespace: !Ref CloudWatchMetricsNS
          MetricName: !Ref CloudWatchMetricName
          MetricValue: 1

  LambdaMetricsAlarm:
    Type: AWS::CloudWatch::Alarm
    DependsOn:
      - AlarmSNSTopic
    Properties:
      AlarmDescription: Lambda custom log alarm
      AlarmName: !Ref LambdaMetricsAlarmName
      AlarmActions:
        - !Ref AlarmSNSTopic
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 5
      EvaluationPeriods: 1
      Statistic: Sum
      MetricName: !Ref CloudWatchMetricName
      Namespace: !Ref CloudWatchMetricsNS
      Period: 300
